### ISSUE TITLE
Error: Cannot find module '@vue/composition-api' after upgrade from 32 to 0.33.1

### ISSUE THREAD

**Issue by lowbits** [nuxt-community/composition-api#692]
**📚 What are you trying to do? Please describe.**
After upgrading the dependency from 0.32.0 to 0.33.1 I get the error. When running yarn dev and yarn build

`Cannot find module '@vue/composition-api' `

**🔍 What have you tried?**
Added `transpile: [/@vue[\\/]composition-api/]` to nuxt config
Removed .nuxt, yarn.lock
Cleaned yarn cache

**ℹ️ Additional context**
Stack Trace:

```
 FATAL  Cannot find module '@vue/composition-api'                                                                     09:38:39
Require stack:
- /Users/_/git/_/node_modules/@nuxtjs/composition-api/dist/runtime/index.js

Require stack:
- /Users/_/git/_/node_modules/@nuxtjs/composition-api/dist/runtime/index.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.resolve (node:internal/modules/cjs/helpers:108:19)
at _resolve (node_modules/jiti/dist/jiti.js:1:243297)
at jiti (node_modules/jiti/dist/jiti.js:1:245423)
at /Users/_/git/_/node_modules/@nuxtjs/composition-api/dist/runtime/index.js:6:24
at jiti (node_modules/jiti/dist/jiti.js:1:247497)
at /Users/_/git/_/dist/composables/basket/useBasket.js:4:27
at jiti (node_modules/jiti/dist/jiti.js:1:247497)
at /Users/_/git/_/dist/index.js:7:19
at jiti (node_modules/jiti/dist/jiti.js:1:247497)
``

**Comment by lowbits** [comment]
Nevermind i think a package I used in my application used still an old version of composition API
