### ISSUE TITLE
fix: Not working in Nuxt < 2.13

### ISSUE THREAD

**Issue by JulianMar** [nuxt-community/composition-api#138]
**🐛 The bug**
If you install the Plugin with Nuxt 2.12 or lower the plugin doesn't work because `TypeError: isFullStatic is not a function`
it's imported from nuxt here https://github.com/nuxt-community/composition-api/blob/ccdd7fe547f2d8ccc593d1226654993b61864e52/src/index.ts#L7

**🛠️ To reproduce**

Just install the plugin on nuxt 2.12 and the error appears

Thanks for the cool plugin :)

**Comment by JulianMar** [comment]
After further investigation, it seems like a issue with nuxt-ts interop

**Comment by JulianMar** [comment]
Okay after multiple deletions of node_modules and package-lock.json I got it working.
No issue with library

**Comment by danielroe** [comment]
Reading through this was quite a drama! Glad things got sorted out.
